### ISSUE TITLE
Versioning of specification documents

### ISSUE THREAD

**Issue by mjacoby** [admin-shell-io/aas-specs-api#145]
On Friday 23.06.2023 an IDTA newsletter was send stating the following

```
Specification of the Asset Administration Shell Part 2: Bugs fixed

The Specification of the Asset Administration Shell Part 2 „Application Programming Interfaces“ (API) describes the interfaces and the APIs in selected technologies for the Asset Administration Shells and its Submodels.

With the implementation, bugs have been noticed that had to be fixed for better applicability. The bug fixes are minor adjustments and do not lead to a new number of the standard. The Specification of the Asset Administration Shell Part 2 "Application Programming Interfaces" is updated under the current publication date and available in our Content Hub.  
```
with a link pointing to the new version of the document https://industrialdigitaltwin.org/en/wp-content/uploads/sites/2/2023/06/IDTA-01002-3-0_SpecificationAssetAdministrationShell_Part2_API_.pdf

After closer inspection, it seems that this document (IDTA number 01002-3-0, Status: June 2023) superseeds the previous version of this document (IDTA number 01002-3-0, Status April 2023). 

I see the following issues with this procedure

- each new document should explicitly state which previous version is supersedes
- each version of the document should have a proper version number following semantic versioning guidelines clearly stated in the preamble/imprint of the document (it seems that the new version is considered v3.0.1 as in the annex/changelog it states `Changes w.r.t. V3.0 to V3.0.1` although v3.0.1 is never properly defined/introduced)
- any releases of the specification should undergo the official review prodecure - this one did not for some reason
- all officially released versions should be available online indefinitely but it seems like the previous version (IDTA number 01002-3-0, Status April 2023) is no longer available on https://industrialdigitaltwin.org/en/content-hub/downloads

**Comment by BirgitBoss** [comment]
Every specification states in chapter "Editorial Notes" that semver is used.
Every specification has an appendix describing the changes compared to the previous version.
Bugfixes do not undergo an official review procedure, all other versions do. Only Bugfixes overwrite previous versions.

**Comment by sebbader-sap** [comment]
Closing this issue as no further action is going to happen.
