### ISSUE TITLE
IdShortPath Serialization

### ISSUE THREAD

**Issue by mjacoby** [admin-shell-io/aas-specs-api#155]
idShortPath serialization does not seem to defined in the level of detail required to actually implement it. Here are some of the issues I identified so far

- What about nested elements, e.g. the inputVariable of an operation, Entity.statement, or AnnotatedRelationshipElement.annotation? Are they just ignored in this serialization format or, if not, how should they be serialized?
- When querying data via the API using idShortPath serialization, are the returned paths expected to be absolute or relativ to the requested element? Is the requested element included or only its children?

  **Example**
  Assuming the following AAS structure
 `Submodel` --> `SubmodelElementCollection` --> `Property`

  What is the expected response when executing `GET` on `/submodel/submodel-elements/SubmodelElementCollection/$path` ?

  1. `[ "Property" ]`
  2. `[ "SubmodelElementCollection.Property" ]`
  3. `[ "Submodel.SubmodelElementCollection.Property" ]`
  4. `[ "SubmodelElementCollection", "Property" ]`
  5. `[ "SubmodelElementCollection", "SubmodelElementCollection.Property" ]`
  6. `[ "Submodel.SubmodelElementCollection", "Submodel.SubmodelElementCollection.Property" ]`

**Comment by mjacoby** [comment]
After discussion with IDTA AAS Cloud Repository Working Group we concluded that the correct answer is

  5. `[ "SubmodelElementCollection", "SubmodelElementCollection.Property" ]`

**Comment by sebbader-sap** [comment]
In Chapter 11.4.4, the example explains "a request for idShort paths starts at MySubmodelElementCollection", and then the result is

```json
[
    "MySubmodelElementCollection",
    "MySubmodelElementCollection.MySubProperty1",
    ...
]
``` 

Therefore, I also say that Option 5 / v is correct. I have added/adjusted the following statements in the V3.0.2 version:

> [...] In any case, the first item of any idShortPath is the idShort if the requested element.
In the following example, where a request for idShort paths targets MySubmodelElementCollection with SerializationModifier level = deep, the list of idShort paths is returned as follows: [...]

**Comment by sebbader-sap** [comment]
Regarding [/aas/submodels/{submodelIdentifier}/$path](https://app.swaggerhub.com/apis/Plattform_i40/Entire-API-Collection/V3.0#/Asset%20Administration%20Shell%20API/GetSubmodel-Path_AAS) vs. 
[/aas/submodels/{submodelIdentifier}/submodel-elements/$path](https://app.swaggerhub.com/apis/Plattform_i40/Entire-API-Collection/V3.0#/Asset%20Administration%20Shell%20API/GetAllSubmodelElementsPath_AAS):

My understanding is that the first one has the Submodel as its target, therefore, the Submodel idShort is the first element. The latter one targets one level deeper. Consequently, the idShortPaths for this one do _not_ start with the Submodel idShort.

**Comment by mjacoby** [comment]
After thinking about this, I think this is not the best solution for the following reasoning:

Adding the current element and therefore "prefixing" all paths with the idShort of the current Element is redundant information. Moreover, it does not follow best-practices for the web. As IdShortPaths are basically the same as a relative link, i.e. you should be able to just add them to the current URL to navigate to respective element. This is not the case when they contain/start with the current element.

Therefore, I propose the following rules for $path serialization

- do not include the requested element
- idShortPath must be returned relative to the requested element


In the following I'll give detailed examples how this should look in practice base on the following AAS model

```
Submodel
    Collection1
        List11
            Property111
            Property112
        List12
            Property121
            Property122
    List2
        Collection21
            Property211
            Property212
        Collection22
            Property221
            Property222
```


**/submodel/$path?level=deep**
```
[ 
    "Collection1",
    "Collection1.List11",
    "Collection1.List11.[0]",
    "Collection1.List11.[1]",
    "Collection1.List12",
    "Collection1.List12.[0]",
    "Collection1.List12.[1]",
    "List2",
    "List2[0]",
    "List2[0].Property211",
    "List2[0].Property212",
    "List2[1]",
    "List2[1].Property221",
    "List2[1].Property222"

]
```

**/submodel/$path?level=core**
```
[ 
    "Collection1",
    "List2"
]
```

**/submodel/submodel-elements/Collection1/$path?level=deep**
```
[
    "List11",
    "List11.[0]",
    "List11.[1]",
    "List12",
    "List12.[0]",
    "List12.[1]"
]
```

**/submodel/submodel-elements/Collection1/$path?level=core**
```
[
    "List11",
    "List12"
]
```

**/submodel/submodel-elements/Collection1.List11/$path?level=deep**
```
[
    "[0]",
    "[1]"
]
```

**/submodel/submodel-elements/Collection1.List11/$path?level=core**
```
[
    "[0]",
    "[1]"
]
```

**/submodel/submodel-elements/Collection1.List11[0]/$path?level=deep**
```
[ ]
```

**/submodel/submodel-elements/Collection1.List11[0]/$path?level=core**
```
[ ]
```


**/submodel/submodel-elements/List2/$path?level=deep**
```
[
    "[0]",
    "[0].Property211",
    "[0].Property212",
    "[1]",
    "[1].Property221",
    "[1].Property222"
]
```

**/submodel/submodel-elements/List2/$path?level=core**
```
[
    "[0]",
    "[1]"
]
```

**/submodel/submodel-elements/List2[0]/$path?level=deep**
```
[
    "Property211",
    "Property212"
]
```

**/submodel/submodel-elements/List2[0]/$path?level=core**
```
[
    "[0]",
    "[1]"
]
```

**/submodel/submodel-elements/List2[0].Property211/$path?level=deep**
```
[ ]
```

**/submodel/submodel-elements/List2[0].Property211/$path?level=core**
```
[ ]
```

What remains is the question what to return when calling /submodel/submodel-elements/$path

The logically-consistent response would be to return an array where each element is the result of a call to the corresponding element, which would look like this

**/submodel/submodel-elements/$path?level=deep**

```
[
    [
        "List11",
        "List11.[0]",
        "List11.[1]",
        "List12",
        "List12.[0]",
        "List12.[1]"
    ],
    [
        "[0]",
        "[0].Property211",
        "[0].Property212",
        "[1]",
        "[1].Property221",
        "[1].Property222"
    ]
]
```

I understand that this is not that useful to a client, as he still needs to know the "top-level" idShort (here: Collection1, List2) and need to figure out which entry belongs to which element. It would be more useful for the client to return the same as for /submodel/$path?level=deep, however, this would disable paging as this returns only a single large JSON array.

I therefore think it would be best to keep things symmetrical and afaik the behavior for /submodel-elements shows this correlation problem for /$value.

@sebbader-sap What do you think about this?

**Comment by sebbader-sap** [comment]
My number one priority at the moment is the V3.0.2 bugfix, and to have a consistent state there...
As long as the old sentence "a request for idShort paths starts at MySubmodelElementCollection" is not obviously _wrong_, we can't change the behaviour in V3.0.2 (and most likely also not in V3.1.0). 

I am aware that I am arguing purely from a formal point of view.
