### ISSUE TITLE
[BUG] Operation GetOperationAsyncStatus returns OperationResult but should return ExecutionState

### ISSUE THREAD

**Issue by mjacoby** [admin-shell-io/aas-specs-api#168]
In specification Part 2 (IDTA number 01002-3-0, June 2023), section 5.3.19, page 42 it states, that the operation `GetOperationAsyncStatus` returns `OperationResult` but this does not seem to match the description that the operations returns the state. Therefore, the return type should be `ExecutionState` as it also does in the corresponding Swagger documents.

- [x] I have signed the required Developer Certificate of Origin ([DCO](https://developercertificate.org)) already.

**Comment by sebbader-sap** [comment]
Will be adjusted in the next bugfix release.

**Comment by g1zzm0** [comment]
Fixed in Version 3.0.2
