### ISSUE TITLE
[BUG] DIN SPEC 16593 linked in PDF

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/aas-specs-api#178]
# What happens?

Part 2 Page 112 contains links to DIN SPEC 16593 in SwaggerHub. 
...

# Why is this wrong?

The DIN SPEC 16593 domain should never appear. Content is part of the Part 2 domain and nothing else.

# How should it be fixed?

Remove all references to DIN SPEC 16593 domain and Swaggerhub resources from the document
...

- [x] I have signed the required Developer Certificate of Origin ([DCO](https://developercertificate.org)) already.

**Comment by sebbader-sap** [comment]
I removed the link from the current working version.

**Comment by BirgitBoss** [comment]
seems to have been fixed in V3.02 or V3.01? Change milestone accordingly?
