### ISSUE TITLE
No use for cursor for /submodel/submodel-elements/{idShortPath}/$metadata ?

### ISSUE THREAD

**Issue by chenliop** [admin-shell-io/aas-specs-api#195]
# What happens?
I'm implementing the submodel api and the cursor seems out of place here, is this a bug?
<img width="358" alt="image" src="https://github.com/admin-shell-io/aas-specs-api/assets/42642230/686429ac-84a8-42d5-ae5b-7fb65efc398d">

https://app.swaggerhub.com/apis/Plattform_i40/SubmodelServiceSpecification/V3.0.1_SSP-001#/Submodel%20API/GetSubmodelElementByPath-Metadata

From my understanding, we are retrieving a single submodel element in it's metadata representation, so the result would only have a single element. E.g. we retrieve an element "SubmodelElementCollection2" with idShortPath "SubmodelElementCollection1.SubmodelElementCollection2"
Since the result will be a metadata representation, the collections value will be empty, so there is nowhere to apply the cursor sensibly, from what I can tell.

# Why is this wrong?
If the result always consists only of a single element, there is no need for a cursor and it's only confusing.

# How should it be fixed?
Remove the cursor from the API definition

- [x ] I have signed the required Developer Certificate of Origin ([DCO](https://developercertificate.org)) already.

**Comment by alexgordtop** [comment]
Confirmed in workstream meeting. Will be fixed in bugfix version.

**Comment by sebbader-sap** [comment]
Solved with #235
