### ISSUE TITLE
Remove Level from Metadata Requests

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/aas-specs-api#249]
# What happens?

"Metadata" has currently "Level" modifiers, both in the OpenAPI descriptions and the examples in the document.
 
# Why is this wrong?

"Metadata" is intended to not give the "values" of an element. "Level" governs the behaviour of the "values". It doesn't make sense to have a parameter controlling something that shouldn't be there.

# How should it be fixed?

Remove "Level" from all "Metadata" requests, add a statement to the document explaining that Metadata must not have a "Level" parameter.

- [x] I have signed the required Developer Certificate of Origin ([DCO](https://developercertificate.org)) already.

**Comment by sebbader-sap** [comment]
I added the following constraint to Chapter 12.8 for version V3.0.2:

> •	The behavior of Level in combination with Content=Metadata. A server may ignore the Level modifier if it is set.

**Comment by sebbader-sap** [comment]
And adjusted the example in Annex C.2 (GET). The one in Annex C.3 (PATCH) seems correct.

**Comment by BirgitBoss** [comment]
When having a look at the table defined which elements are not parts of metadata:
I wonder why really all attributes of BasicEventElement are displayed except for "observed". Probably "obsered" is the only one that could be useful as metadata? But what about state, direction etc.?

**Comment by sebbader-sap** [comment]
> When having a look at the table defined which elements are not parts of metadata: I wonder why really all attributes of BasicEventElement are displayed except for "observed". Probably "observed" is the only one that could be useful as metadata? But what about state, lastUpdate etc.?
> 
> In V3.1 Entity/entityType is optional. So it might be ommitted as well.
> 
> assetInformation is extremly important for AAS. At least the globalAssetId should be availabel in metadata Format as well?
> 
> What about concept descriptions? Is there a metadata API for concept description repository? https://app.swaggerhub.com/apis/Plattform_i40/ConceptDescriptionRepositoryServiceSpecification/V3.0.1_SSP-001#/Concept%20Description%20Repository%20API/GetConceptDescriptionById: no metadata Format for concept descriptions

Finding has been moved to a new issue (see #257 )

**Comment by sebbader-sap** [comment]
PR is merged, additional finding in new issue, therefore, closing this one.
