### ISSUE TITLE
Unknown `IdShortType` referenced

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-api#274]
In the `ProtocolInformation` Table the `IdShortType` is referenced. Is it a typo and should it be replaced with `ShortIdType`?

https://github.com/admin-shell-io/aas-specs-api/blob/0252e57650ca84d9a6e369c444d2c3279fd059ec/documentation/IDTA-01002-3/modules/ROOT/pages/IDTA-01002_Spec_InterfacesPayload.adoc?plain=1#L156

**Comment by sebbader-sap** [comment]
Thanks for the finding, please have a look at the related PR and review it quickly.

**Comment by zrgt** [comment]
Fixed in #276
