### ISSUE TITLE
Duplicate query parameters such as `level`

### ISSUE THREAD

**Issue by mjacoby** [admin-shell-io/aas-specs-api#313]
It is currently undefined what is the expected result when using duplicate query parameters, e.g., GET `/submodel?level=core&level=deep`.

I see the following possible solutions

- use first occurance
- use last occurance
- return `400 Bad Request`
- leave it undefined in the specification but add a section that we are aware of the issue and it is strongly discouraged to make requests with duplicates query parameters as the result might not be deterministic. The reasoning behind this is that many HTTP libraries across different programming languages actually resolve this differently sometimes even hiding from the application that they remove duplicate query parameters.

We discussed this in the IDTA Test Engine Developer Group and propose to use the last solution and leave this undefined and also do not test it.

- [x] I have signed the required Developer Certificate of Origin ([DCO](https://developercertificate.org)) already.

**Comment by sebbader-sap** [comment]
Proposal: Add a Note to the next release stating that the server can decide on the selected parameter. It is of course generally discouraged to send these query parameters more than once.

**Comment by sebbader-sap** [comment]
Solved with #336
